TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: 0.005
  max_vel_theta: 3.0
  min_vel_theta: -3.0
  min_in_place_vel_theta: 6.0
  acc_lim_theta: 5
  acc_lim_x: 5
  acc_lim_y: 5
  holonomic_robot: false