TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: 0.01/2
  max_vel_theta: 4.0
  min_vel_theta: -4.0
  min_in_place_vel_theta: 0.9
  acc_lim_theta: 4.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  holonomic_robot: false


  # max_vel_x: 1.0
  # min_vel_x: 0.01/2
  # max_vel_theta: 3.0
  # min_vel_theta: -3.0
  # min_in_place_vel_theta: 4.0
  # acc_lim_theta: 3.0
  # acc_lim_x: 3.0
  # acc_lim_y: 3.0
  # holonomic_robot: false

  # max_vel_x: 1.0
  # min_vel_x: 0.01/2
  # max_vel_theta: 3.5
  # min_vel_theta: -3.5
  # min_in_place_vel_theta: 0.6
  # acc_lim_theta: 3.0
  # acc_lim_x: 2.5
  # acc_lim_y: 2.5
  # holonomic_robot: false

  # max_vel_x: 1.0
  # min_vel_x: 0.01/2
  # max_vel_theta: 3.0
  # min_vel_theta: -3.0
  # min_in_place_vel_theta: 0.6
  # acc_lim_theta: 3.0
  # acc_lim_x: 2.5
  # acc_lim_y: 2.5
  # holonomic_robot: false